import { Link } from 'react-router-dom';

export const EducationalHub = () => {
  return (
    <div className="container main-content animate-fade-in">
      <div className="glass-panel" style={{ maxWidth: '800px', margin: '0 auto' }}>
        <h1 className="text-center mb-8">Understanding Your Carbon Footprint</h1>
        
        <section className="mb-8">
          <h2>What is a Carbon Footprint?</h2>
          <p className="mt-4 text-lg" style={{ lineHeight: '1.6' }}>
            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. 
            The average carbon footprint for a person in the United States is <strong>16 tons</strong>, one of the highest rates in the world. 
            Globally, the average is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global 
            carbon footprint per year needs to drop under 2 tons by 2050.
          </p>
        </section>

        <section className="mb-8">
          <h2>The Impact of Diet</h2>
          <div className="grid md:grid-cols-2 gap-4 mt-4">
            <div className="glass-panel p-4">
              <h3 className="text-accent mb-2">Meat-Heavy Diet</h3>
              <p>Emits roughly <strong>3,300 kg CO₂e</strong> per year. Beef and lamb have the highest footprint of any food per gram of protein.</p>
            </div>
            <div className="glass-panel p-4">
              <h3 className="text-accent mb-2">Vegan Diet</h3>
              <p>Emits roughly <strong>1,500 kg CO₂e</strong> per year. A plant-based diet can cut your food-related emissions by over 50%.</p>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2>Transportation Matters</h2>
          <p className="mt-4" style={{ lineHeight: '1.6' }}>
            A typical passenger vehicle emits about <strong>4.6 metric tons of carbon dioxide per year</strong>. 
            Every gallon of gasoline burned creates about 8,887 grams of CO₂. By reducing your driving by just 10% 
            (roughly 1,000 miles a year for the average driver), you can save over 400 kg of CO₂.
          </p>
        </section>

        <section className="mb-8">
          <h2>Energy Usage at Home</h2>
          <p className="mt-4" style={{ lineHeight: '1.6' }}>
            Electricity generation is a major contributor to climate change. The exact impact depends on your local power grid 
            (coal vs. renewables). However, simple changes like switching to LED bulbs, washing clothes in cold water, and 
            improving home insulation can reduce your energy footprint by up to 20%.
          </p>
        </section>

        <div className="text-center mt-12">
          <Link to="/calculator" className="btn btn-primary text-lg px-8 py-3">
            Calculate Your Footprint Now
          </Link>
        </div>
      </div>
    </div>
  );
};
